version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/urlshortener
      - SPRING_DATA_REDIS_HOST=redis
  
  mongodb:
    image: mongo:7
    ports:
      - "27019:27017"
  
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"