# Common configurations across all profiles
spring:
  application:
    name: url-shortener
  
  # Default profile if none specified
  profiles:
    default: dev
    
  # Common Jackson configuration
  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Common server configuration
server:
  error:
    include-message: on-param
    include-binding-errors: on-param